jobs:
 build:
   docker:
     - image: maven:3.3-jdk-8
     
   working_directory: ~/repo
   
     
   steps:
     - checkout:
     - run:
        name: Download Selenium
        command: |
         curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      
     - run:
        name: Start Selenium
        command: |
         wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
         sudo dpkg -i google-chrome-stable_current_amd64.deb
         chromeVersion=$(google-chrome --product-version | sed 's/\..*//')
         latestChromeDriverURL=$(wget http://chromedriver.storage.googleapis.com/LATEST_RELEASE_$chromeVersion -q -O -)
         echo $latestChromeDriverURL
         wget "http://chromedriver.storage.googleapis.com/${latestChromeDriverURL}/chromedriver_linux64.zip"
         unzip chromedriver_linux64.zip -d chromedriver
         chmod +x chromedriver
         export PATH="$PWD/chromedriver:$PATH"
        background: true
     - run:
        command: |
         pwd
         ls -a
     - run:
        command: mvn install

     - run:
        name: Run test via maven
        command: mvn test
