version: 2

jobs:
 test_exec:
   docker:
     - image: maven:3.3-jdk-8
   steps:
     - checkout
     - run:
        command: mvn install

     - run:
         name: Run test via maven
         command: mvn test
