jobs:
 build:
   docker:
     - image: maven:3.3-jdk-8
     
   working_directory: ~/repo
   
     
   steps:
     - checkout:
      - run:
          name: Download Selenium
          command: |
            curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      
      - run:
          name: Start Selenium
          command: |
            java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
          background: true
     - run:
        command: |
         pwd
         ls -a
     - run:
        command: mvn install

     - run:
        name: Run test via maven
        command: mvn test
